# Generated by Django 6.0.2 on 2026-03-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localevents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
