# Generated by Django 6.0.3 on 2026-05-03 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('localevents', '0002_event_updated_on_alter_event_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_capacity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.ImageField(default='.static/img/csci_default_img.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.ManyToManyField(to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Full', 'Full'), ('Done', 'Done'), ('Cancelled', 'Cancelled')], default='Available'),
        ),
        migrations.CreateModel(
            name='EventSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_registrant', models.CharField()),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_signup', to='localevents.event')),
                ('user_registrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
