# Generated by Django 6.0.3 on 2026-05-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localevents', '0003_event_event_capacity_event_event_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_capacity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Full', 'Full'), ('Done', 'Done'), ('Cancelled', 'Cancelled')], null=True),
        ),
    ]
