# Generated by Django 6.0.3 on 2026-05-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('localevents', '0004_alter_event_event_capacity_alter_event_event_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ManyToManyField(related_name='organizer', to='accounts.profile'),
        ),
    ]
