# Generated by Django 6.0.3 on 2026-05-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localevents', '0005_alter_event_event_image_alter_event_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(default='media/images/csci_default_img.png', upload_to='images/'),
        ),
    ]
