# Generated by Django 6.0.3 on 2026-05-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localevents', '0006_alter_event_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(default='.media/images/csci_default_img.png', upload_to='images/'),
        ),
    ]
