# Generated by Django 6.0.3 on 2026-05-07 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_role'),
        ('localevents', '0007_alter_event_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsignup',
            name='new_registrant',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='eventsignup',
            name='user_registrant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_signups', to='accounts.profile'),
        ),
    ]
