# Generated by Django 6.0.3 on 2026-05-07 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localevents', '0008_alter_eventsignup_new_registrant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsignup',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_signup', to='localevents.event'),
        ),
    ]
