# Generated by Django 6.0.3 on 2026-05-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_role'),
        ('localevents', '0009_alter_eventsignup_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ManyToManyField(blank=True, related_name='organizer', to='accounts.profile'),
        ),
    ]
