# Generated by Django 6.0.3 on 2026-05-07 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_role'),
        ('localevents', '0011_alter_event_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsignup',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_signup', to='localevents.event'),
        ),
        migrations.AlterField(
            model_name='eventsignup',
            name='user_registrant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_signup', to='accounts.profile'),
        ),
    ]
