# Generated by Django 6.0.3 on 2026-05-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0004_alter_bookreview_anon_reviewer_alter_bookreview_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='date_bookmarked',
            field=models.DateField(auto_now_add=True),
        ),
    ]
