# Generated by Django 6.0.1 on 2026-05-04 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='maker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='accounts.profile'),
        ),
        migrations.AddField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('F', 'Full')], default=('O', 'Open')),
        ),
        migrations.AddField(
            model_name='commission',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission', to='commissions.commissiontype'),
        ),
    ]
