# Generated by Django 6.0.1 on 2026-05-05 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('commissions', '0004_alter_commission_maker_alter_commission_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_application', to='accounts.profile'),
        ),
    ]
