# Generated by Django 6.0.1 on 2026-05-07 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0007_alter_jobapplication_applicant_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commission',
            options={'ordering': ['-status', '-created_on']},
        ),
    ]
