# Generated by Django 6.0.1 on 2026-05-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0008_alter_commission_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, choices=[('OPEN', 'Open'), ('FULL', 'Full')], default=('OPEN', 'Open')),
        ),
    ]
