# Generated by Django 6.0.1 on 2026-05-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0009_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='manpower_required',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='role',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
