# Generated by Django 6.0.1 on 2026-05-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0010_alter_job_manpower_required_alter_job_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='manpower_required',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='role',
            field=models.CharField(max_length=255),
        ),
    ]
