# Generated by Django 6.0.4 on 2026-05-01 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diyprojects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_on']},
        ),
    ]
